---
- name: Prepare Wordpress directory
  ansible.builtin.file:
    path: "/var/www/{{ wp_host }}"
    state: directory
    
- name: WordPress download and unpackage
  ansible.builtin.unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ wp_host }}"
    remote_src: yes
    extra_opts:
    - --strip-components=1

- name: Set up wp-config 
  ansible.builtin.template:
    src: "roles/wordpress_role/templates/wp-config.php.j2"
    dest: "/var/www/{{ wp_host }}/wp-config.php"
  notify: Restart Apache2  
  
- name: Change ownership and permissions for Wordpress directory
  ansible.builtin.file:
    path: "/var/www/{{ wp_host }}"
    state: directory
    recurse: true
    owner: www-data
    group: www-data
    mode: 0755

