- name: Find environment via hostname
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Find environment via hostname
      ansible.builtin.set_fact:
        host_environment: azure-dr
        mysql_db_host: "10.0.2.4"
        mysql_db: "mysql_neu_dr"
      when: lookup('pipe','hostname')=="grupo4-neu-dr-vm-cn"

    - name: Find environment via hostname
      ansible.builtin.set_fact:
        host_environment: azure-prod
        mysql_db_host: "10.1.6.4"
        mysql_db: "mysql_weu_prod"
      when: lookup('pipe','hostname')=="grupo4-weu-prod-vm-cn"