---
- name: Patching and Updating all systems
  hosts: all
  tasks:
    - name: Update Debian-based systems databases
      become: yes
      ansible.builtin.apt:
        update_cache: true
        upgrade: "yes"
      when: ansible_os_family == 'Debian'
    
    - name: Update Windows systems databases
      ansible.windows.win_updates:
        category_names: "*"
        state: searched
      register: win_updates_results
      when: ansible_os_family == 'Windows'

    - name: Reboot Windows if necessary
      ansible.windows.win_reboot:
      when: 
        - ansible_os_family == 'Windows'
        - win_updates_results.reboot_required == true


    - name: Install security updates
      ansible.windows.win_updates:
        category_names: "*"
        state: installed
      register: win_upgrades_results
      when: 
        - ansible_os_family == 'Windows'
        - win_updates_results.updates | length > 0
        

